### ISSUE TITLE
Profile name resolution for a dataset in "Favorites" 

### ISSUE THREAD

**Issue by venkatzhub** [HCLmainframetools/mainframeToolsDocs#3]
I have the HCL z Tools installed. 

I open a JCL dataset member from the Favorites node where I added a JCL dataset from the only profile I had created. 

I right click in the editor and choose the Submit Job - and it returns with an error message saying: Could not get a profile named "Favorites". 

The Submit Job from the editor does work when I submit the job for the data set that is opened from the actual profile "node" - but not the Favorites.

**Comment by travatine** [comment]
Hi @venkatzhub ,

There is two problems I can see here, 
1 Zowe explorer is putting "favorite" instead of the actual profile name in the document path. I have opened an issue on Zowe explorer git about this: https://github.com/zowe/vscode-extension-for-zowe/issues/778

2 Hcl z Tools should be checking for a profile name of "Favorite" and instead prompting the user for a profile name.

I will fix (2) as part of the next update of HCL z Tools.
Could you please upvote the issue I have opened on Zowe explorer GitHub #778 , that might encourage Zowe team to fix it in the next release.

**Comment by venkatzhub** [comment]
I added a comment to that issue, I prefer having an API call that the extenders can rely on to figure out what profile a resource belongs to rather than parsing document paths.

**Comment by travatine** [comment]
Hi @venkatzhub , 
Thanks for updating the zowe explorer issue.
I've just published "HCL z Tools 0.0.6" ; it includes the fix for this issue;

![Untitled Project](https://user-images.githubusercontent.com/17565183/81254356-78b97600-905d-11ea-993c-c8d798c3d1dd.gif)

Thanks

**Comment by travatine** [comment]
Hi,
I'm guessing this is now resolved, please reopen this issue if not.
